--liquibase formatted sql

--changeset dev:01-create-schema
CREATE TABLE families (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL UNIQUE,
                          treasury_balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(100) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL,
                       family_id BIGINT,
                       photo_url VARCHAR(500),
                       bio TEXT,
                       CONSTRAINT fk_users_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE SET NULL
);

CREATE TABLE businesses (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(150) NOT NULL,
                            type VARCHAR(100) NOT NULL,
                            weekly_revenue DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
                            capo_id BIGINT UNIQUE,
                            family_id BIGINT NOT NULL,
                            CONSTRAINT fk_businesses_capo FOREIGN KEY (capo_id) REFERENCES users(id) ON DELETE SET NULL,
                            CONSTRAINT fk_businesses_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE
);

CREATE TABLE financial_ledger (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  family_id BIGINT NOT NULL,
                                  capo_id BIGINT NOT NULL,
                                  amount DECIMAL(15, 2) NOT NULL,
                                  contributed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  description VARCHAR(500),
                                  CONSTRAINT fk_ledger_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE,
                                  CONSTRAINT fk_ledger_capo FOREIGN KEY (capo_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE messages (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          sender_id BIGINT NOT NULL,
                          recipient_id BIGINT NOT NULL,
                          subject VARCHAR(255) NOT NULL,
                          body TEXT NOT NULL,
                          sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
                          CONSTRAINT fk_messages_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE family_relations (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  family_1_id BIGINT NOT NULL,
                                  family_2_id BIGINT NOT NULL,
                                  status VARCHAR(50) NOT NULL DEFAULT 'PEACE',
                                  CONSTRAINT fk_relations_family1 FOREIGN KEY (family_1_id) REFERENCES families(id) ON DELETE CASCADE,
                                  CONSTRAINT fk_relations_family2 FOREIGN KEY (family_2_id) REFERENCES families(id) ON DELETE CASCADE,
                                  CONSTRAINT uq_family_pair UNIQUE (family_1_id, family_2_id),
                                  CONSTRAINT chk_family_order CHECK (family_1_id < family_2_id)
);

CREATE TABLE articles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          title VARCHAR(255) NOT NULL,
                          content TEXT NOT NULL,
                          is_public BOOLEAN NOT NULL DEFAULT TRUE,
                          family_id BIGINT,
                          CONSTRAINT fk_articles_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE SET NULL
);